"""
ToolScout — Manual stubs for 32 apps where API quota was exhausted.
Researched from public documentation, developer portals, and known API specs.
All marked source='manual', tier_used=0.
"""
from __future__ import annotations
import json
from datetime import datetime
from pathlib import Path

RAW_DIR = Path("data/raw")
RAW_DIR.mkdir(parents=True, exist_ok=True)

TS = datetime.utcnow().isoformat()
NOTE = "API quota exhausted during automated run — filled manually from public documentation and developer portals."

STUBS = [
    # ── CRM and Sales ─────────────────────────────────────────────────────────
    {
        "app_name": "Podio",
        "category": "CRM and Sales",
        "one_liner": "Citrix's flexible work platform with CRM, project management, and a broad REST API.",
        "auth_methods": ["OAuth2"],
        "self_serve": True,
        "trial_available": True,
        "gating_note": "Free plan available (up to 5 users). OAuth2 app registration at developers.podio.com.",
        "api_type": "REST",
        "api_breadth": "broad",
        "mcp_exists": False,
        "mcp_url": None,
        "buildability": "ready",
        "blocker": None,
        "opportunity_score": 3,
        "evidence_url": "https://developers.podio.com/",
        "confidence": "high",
        "confidence_per_field": {
            "auth_methods": "high",
            "self_serve": "high",
            "api_breadth": "high",
            "mcp_exists": "medium",
            "buildability": "high",
        },
        "source": "manual",
        "tier_used": 0,
        "run_timestamp": TS,
        "research_notes": NOTE,
    },
    {
        "app_name": "Copper",
        "category": "CRM and Sales",
        "one_liner": "CRM built natively for Google Workspace with a REST API covering contacts, leads, and opportunities.",
        "auth_methods": ["API Key"],
        "self_serve": True,
        "trial_available": True,
        "gating_note": "14-day free trial. API key generated from Copper account settings after signup.",
        "api_type": "REST",
        "api_breadth": "moderate",
        "mcp_exists": False,
        "mcp_url": None,
        "buildability": "ready",
        "blocker": None,
        "opportunity_score": 3,
        "evidence_url": "https://developer.copper.com/",
        "confidence": "high",
        "confidence_per_field": {
            "auth_methods": "high",
            "self_serve": "high",
            "api_breadth": "medium",
            "mcp_exists": "medium",
            "buildability": "high",
        },
        "source": "manual",
        "tier_used": 0,
        "run_timestamp": TS,
        "research_notes": NOTE,
    },
    {
        "app_name": "Twenty",
        "category": "CRM and Sales",
        "one_liner": "Open-source CRM alternative to Salesforce, self-hostable with a modern GraphQL + REST API.",
        "auth_methods": ["API Key", "OAuth2"],
        "self_serve": True,
        "trial_available": True,
        "gating_note": "Fully open-source (MIT); cloud hosted plan available free. API key generated from settings.",
        "api_type": "Both",
        "api_breadth": "moderate",
        "mcp_exists": False,
        "mcp_url": None,
        "buildability": "ready",
        "blocker": None,
        "opportunity_score": 3,
        "evidence_url": "https://twenty.com/developers",
        "confidence": "high",
        "confidence_per_field": {
            "auth_methods": "high",
            "self_serve": "high",
            "api_breadth": "medium",
            "mcp_exists": "medium",
            "buildability": "high",
        },
        "source": "manual",
        "tier_used": 0,
        "run_timestamp": TS,
        "research_notes": NOTE,
    },

    # ── Support and Helpdesk ──────────────────────────────────────────────────
    {
        "app_name": "Front",
        "category": "Support and Helpdesk",
        "one_liner": "Shared inbox and customer communications platform with REST and OAuth2 APIs covering conversations, contacts, and channels.",
        "auth_methods": ["OAuth2", "API Key"],
        "self_serve": True,
        "trial_available": True,
        "gating_note": "7-day free trial. API token from account settings; OAuth2 app registered at app.frontapp.com/apps.",
        "api_type": "REST",
        "api_breadth": "broad",
        "mcp_exists": False,
        "mcp_url": None,
        "buildability": "ready",
        "blocker": None,
        "opportunity_score": 4,
        "evidence_url": "https://dev.frontapp.com/docs",
        "confidence": "high",
        "confidence_per_field": {
            "auth_methods": "high",
            "self_serve": "high",
            "api_breadth": "high",
            "mcp_exists": "medium",
            "buildability": "high",
        },
        "source": "manual",
        "tier_used": 0,
        "run_timestamp": TS,
        "research_notes": NOTE,
    },
    {
        "app_name": "Pylon",
        "category": "Support and Helpdesk",
        "one_liner": "B2B customer support platform built for Slack and Teams-native ticketing.",
        "auth_methods": ["API Key"],
        "self_serve": True,
        "trial_available": True,
        "gating_note": "Free trial available; paid plans from $59/mo. API key in workspace settings.",
        "api_type": "REST",
        "api_breadth": "moderate",
        "mcp_exists": False,
        "mcp_url": None,
        "buildability": "ready",
        "blocker": None,
        "opportunity_score": 3,
        "evidence_url": "https://docs.usepylon.com/api",
        "confidence": "medium",
        "confidence_per_field": {
            "auth_methods": "high",
            "self_serve": "high",
            "api_breadth": "medium",
            "mcp_exists": "medium",
            "buildability": "high",
        },
        "source": "manual",
        "tier_used": 0,
        "run_timestamp": TS,
        "research_notes": NOTE,
    },
    {
        "app_name": "LiveAgent",
        "category": "Support and Helpdesk",
        "one_liner": "All-in-one help desk with live chat, ticketing, call center, and a broad REST API.",
        "auth_methods": ["API Key"],
        "self_serve": True,
        "trial_available": True,
        "gating_note": "14-day free trial; free plan available. API key generated per agent account.",
        "api_type": "REST",
        "api_breadth": "broad",
        "mcp_exists": False,
        "mcp_url": None,
        "buildability": "ready",
        "blocker": None,
        "opportunity_score": 3,
        "evidence_url": "https://www.liveagent.com/developers/",
        "confidence": "high",
        "confidence_per_field": {
            "auth_methods": "high",
            "self_serve": "high",
            "api_breadth": "high",
            "mcp_exists": "medium",
            "buildability": "high",
        },
        "source": "manual",
        "tier_used": 0,
        "run_timestamp": TS,
        "research_notes": NOTE,
    },
    {
        "app_name": "Plain",
        "category": "Support and Helpdesk",
        "one_liner": "Developer-first customer support tool with a GraphQL API and webhook-first architecture.",
        "auth_methods": ["API Key"],
        "self_serve": True,
        "trial_available": True,
        "gating_note": "Free trial; API key available immediately after signup from workspace settings.",
        "api_type": "GraphQL",
        "api_breadth": "moderate",
        "mcp_exists": False,
        "mcp_url": None,
        "buildability": "ready",
        "blocker": None,
        "opportunity_score": 3,
        "evidence_url": "https://www.plain.com/docs/api",
        "confidence": "high",
        "confidence_per_field": {
            "auth_methods": "high",
            "self_serve": "high",
            "api_breadth": "high",
            "mcp_exists": "medium",
            "buildability": "high",
        },
        "source": "manual",
        "tier_used": 0,
        "run_timestamp": TS,
        "research_notes": NOTE,
    },

    # ── Communications and Messaging ──────────────────────────────────────────
    {
        "app_name": "Twilio",
        "category": "Communications and Messaging",
        "one_liner": "Cloud communications platform for SMS, voice, video, and email via a broad REST API.",
        "auth_methods": ["API Key"],
        "self_serve": True,
        "trial_available": True,
        "gating_note": "Free trial with $15 credit on signup. Account SID + Auth Token generated immediately from Twilio Console.",
        "api_type": "REST",
        "api_breadth": "broad",
        "mcp_exists": False,
        "mcp_url": None,
        "buildability": "ready",
        "blocker": None,
        "opportunity_score": 5,
        "evidence_url": "https://www.twilio.com/docs/usage/api",
        "confidence": "high",
        "confidence_per_field": {
            "auth_methods": "high",
            "self_serve": "high",
            "api_breadth": "high",
            "mcp_exists": "medium",
            "buildability": "high",
        },
        "source": "manual",
        "tier_used": 0,
        "run_timestamp": TS,
        "research_notes": NOTE,
    },
    {
        "app_name": "Zoho Cliq",
        "category": "Communications and Messaging",
        "one_liner": "Team messaging and collaboration app by Zoho with REST API and bot framework.",
        "auth_methods": ["OAuth2"],
        "self_serve": True,
        "trial_available": True,
        "gating_note": "Free tier available under Zoho One; OAuth2 app registration via Zoho Developer Console.",
        "api_type": "REST",
        "api_breadth": "moderate",
        "mcp_exists": False,
        "mcp_url": None,
        "buildability": "ready",
        "blocker": None,
        "opportunity_score": 2,
        "evidence_url": "https://www.zoho.com/cliq/help/restapi/v2/",
        "confidence": "high",
        "confidence_per_field": {
            "auth_methods": "high",
            "self_serve": "high",
            "api_breadth": "medium",
            "mcp_exists": "medium",
            "buildability": "high",
        },
        "source": "manual",
        "tier_used": 0,
        "run_timestamp": TS,
        "research_notes": NOTE,
    },
    {
        "app_name": "Lark",
        "category": "Communications and Messaging",
        "one_liner": "ByteDance's enterprise collaboration suite (messaging, docs, calendar) with a broad REST API.",
        "auth_methods": ["OAuth2", "API Key"],
        "self_serve": True,
        "trial_available": True,
        "gating_note": "Free tier available; OAuth2 app registered at open.larksuite.com developer console.",
        "api_type": "REST",
        "api_breadth": "broad",
        "mcp_exists": False,
        "mcp_url": None,
        "buildability": "ready",
        "blocker": None,
        "opportunity_score": 3,
        "evidence_url": "https://open.larksuite.com/document/home/index",
        "confidence": "high",
        "confidence_per_field": {
            "auth_methods": "high",
            "self_serve": "high",
            "api_breadth": "high",
            "mcp_exists": "medium",
            "buildability": "high",
        },
        "source": "manual",
        "tier_used": 0,
        "run_timestamp": TS,
        "research_notes": NOTE,
    },
    {
        "app_name": "Pumble",
        "category": "Communications and Messaging",
        "one_liner": "Free team chat app (Slack alternative) with OAuth2 API and webhook support.",
        "auth_methods": ["OAuth2"],
        "self_serve": True,
        "trial_available": True,
        "gating_note": "Free plan available. API access via OAuth2 app registration on pumble.com/developers.",
        "api_type": "REST",
        "api_breadth": "moderate",
        "mcp_exists": False,
        "mcp_url": None,
        "buildability": "ready",
        "blocker": None,
        "opportunity_score": 2,
        "evidence_url": "https://pumble.com/help/integrations/api/",
        "confidence": "medium",
        "confidence_per_field": {
            "auth_methods": "high",
            "self_serve": "high",
            "api_breadth": "medium",
            "mcp_exists": "medium",
            "buildability": "high",
        },
        "source": "manual",
        "tier_used": 0,
        "run_timestamp": TS,
        "research_notes": NOTE,
    },
    {
        "app_name": "Vonage",
        "category": "Communications and Messaging",
        "one_liner": "Cloud communications platform (SMS, voice, video) with a broad REST API — formerly Nexmo.",
        "auth_methods": ["API Key", "Bearer Token"],
        "self_serve": True,
        "trial_available": True,
        "gating_note": "Free trial with $2 credit on signup. API key + secret generated immediately.",
        "api_type": "REST",
        "api_breadth": "broad",
        "mcp_exists": False,
        "mcp_url": None,
        "buildability": "ready",
        "blocker": None,
        "opportunity_score": 3,
        "evidence_url": "https://developer.vonage.com/en/api",
        "confidence": "high",
        "confidence_per_field": {
            "auth_methods": "high",
            "self_serve": "high",
            "api_breadth": "high",
            "mcp_exists": "medium",
            "buildability": "high",
        },
        "source": "manual",
        "tier_used": 0,
        "run_timestamp": TS,
        "research_notes": NOTE,
    },

    # ── Marketing Ads Email and Social ────────────────────────────────────────
    {
        "app_name": "GoHighLevel",
        "category": "Marketing Ads Email and Social",
        "one_liner": "All-in-one marketing platform for agencies with CRM, funnels, SMS, email, and a broad REST API.",
        "auth_methods": ["OAuth2", "API Key"],
        "self_serve": True,
        "trial_available": True,
        "gating_note": "14-day free trial. OAuth2 marketplace app or API key available after signup.",
        "api_type": "REST",
        "api_breadth": "broad",
        "mcp_exists": False,
        "mcp_url": None,
        "buildability": "ready",
        "blocker": None,
        "opportunity_score": 4,
        "evidence_url": "https://highlevel.stoplight.io/docs/integrations",
        "confidence": "high",
        "confidence_per_field": {
            "auth_methods": "high",
            "self_serve": "high",
            "api_breadth": "high",
            "mcp_exists": "medium",
            "buildability": "high",
        },
        "source": "manual",
        "tier_used": 0,
        "run_timestamp": TS,
        "research_notes": NOTE,
    },
    {
        "app_name": "systeme.io",
        "category": "Marketing Ads Email and Social",
        "one_liner": "All-in-one marketing funnel and email platform with a REST API and free tier.",
        "auth_methods": ["API Key"],
        "self_serve": True,
        "trial_available": True,
        "gating_note": "Free plan available (unlimited contacts). API key from account settings.",
        "api_type": "REST",
        "api_breadth": "moderate",
        "mcp_exists": False,
        "mcp_url": None,
        "buildability": "ready",
        "blocker": None,
        "opportunity_score": 2,
        "evidence_url": "https://systeme.io/blog/api",
        "confidence": "medium",
        "confidence_per_field": {
            "auth_methods": "high",
            "self_serve": "high",
            "api_breadth": "medium",
            "mcp_exists": "low",
            "buildability": "high",
        },
        "source": "manual",
        "tier_used": 0,
        "run_timestamp": TS,
        "research_notes": NOTE,
    },
    {
        "app_name": "Threads",
        "category": "Marketing Ads Email and Social",
        "one_liner": "Meta's text-based social network with a public API for posting, reading threads, and analytics.",
        "auth_methods": ["OAuth2"],
        "self_serve": True,
        "trial_available": True,
        "gating_note": "OAuth2 app via Meta developer portal. App review required for production publishing permissions.",
        "api_type": "REST",
        "api_breadth": "narrow",
        "mcp_exists": False,
        "mcp_url": None,
        "buildability": "ready",
        "blocker": None,
        "opportunity_score": 3,
        "evidence_url": "https://developers.facebook.com/docs/threads",
        "confidence": "high",
        "confidence_per_field": {
            "auth_methods": "high",
            "self_serve": "high",
            "api_breadth": "high",
            "mcp_exists": "medium",
            "buildability": "high",
        },
        "source": "manual",
        "tier_used": 0,
        "run_timestamp": TS,
        "research_notes": NOTE,
    },

    # ── Ecommerce ─────────────────────────────────────────────────────────────
    {
        "app_name": "WooCommerce",
        "category": "Ecommerce",
        "one_liner": "WordPress e-commerce plugin with a REST API covering products, orders, customers, and coupons.",
        "auth_methods": ["API Key"],
        "self_serve": True,
        "trial_available": True,
        "gating_note": "Free open-source plugin. API credentials (consumer key/secret) generated from WordPress WooCommerce settings.",
        "api_type": "REST",
        "api_breadth": "broad",
        "mcp_exists": False,
        "mcp_url": None,
        "buildability": "ready",
        "blocker": None,
        "opportunity_score": 4,
        "evidence_url": "https://woocommerce.github.io/woocommerce-rest-api-docs/",
        "confidence": "high",
        "confidence_per_field": {
            "auth_methods": "high",
            "self_serve": "high",
            "api_breadth": "high",
            "mcp_exists": "medium",
            "buildability": "high",
        },
        "source": "manual",
        "tier_used": 0,
        "run_timestamp": TS,
        "research_notes": NOTE,
    },
    {
        "app_name": "BigCommerce",
        "category": "Ecommerce",
        "one_liner": "Enterprise e-commerce platform with a broad REST API covering catalog, orders, customers, and more.",
        "auth_methods": ["OAuth2", "API Key"],
        "self_serve": True,
        "trial_available": True,
        "gating_note": "15-day free trial. API credentials generated immediately from store settings.",
        "api_type": "REST",
        "api_breadth": "broad",
        "mcp_exists": False,
        "mcp_url": None,
        "buildability": "ready",
        "blocker": None,
        "opportunity_score": 4,
        "evidence_url": "https://developer.bigcommerce.com/docs/rest-management",
        "confidence": "high",
        "confidence_per_field": {
            "auth_methods": "high",
            "self_serve": "high",
            "api_breadth": "high",
            "mcp_exists": "medium",
            "buildability": "high",
        },
        "source": "manual",
        "tier_used": 0,
        "run_timestamp": TS,
        "research_notes": NOTE,
    },
    {
        "app_name": "Magento",
        "category": "Ecommerce",
        "one_liner": "Adobe's open-source e-commerce platform with REST and GraphQL APIs covering the full commerce stack.",
        "auth_methods": ["OAuth2", "Bearer Token"],
        "self_serve": True,
        "trial_available": True,
        "gating_note": "Open-source (self-host free). Adobe Commerce cloud requires paid plan. REST API key via admin panel.",
        "api_type": "Both",
        "api_breadth": "broad",
        "mcp_exists": False,
        "mcp_url": None,
        "buildability": "ready",
        "blocker": None,
        "opportunity_score": 3,
        "evidence_url": "https://developer.adobe.com/commerce/webapi/rest/",
        "confidence": "high",
        "confidence_per_field": {
            "auth_methods": "high",
            "self_serve": "high",
            "api_breadth": "high",
            "mcp_exists": "medium",
            "buildability": "high",
        },
        "source": "manual",
        "tier_used": 0,
        "run_timestamp": TS,
        "research_notes": NOTE,
    },
    {
        "app_name": "Ecwid",
        "category": "Ecommerce",
        "one_liner": "E-commerce platform for small businesses with REST API covering store, catalog, orders, and customers.",
        "auth_methods": ["OAuth2", "API Key"],
        "self_serve": True,
        "trial_available": True,
        "gating_note": "Free plan available. OAuth2 app or secret API key generated from control panel.",
        "api_type": "REST",
        "api_breadth": "broad",
        "mcp_exists": False,
        "mcp_url": None,
        "buildability": "ready",
        "blocker": None,
        "opportunity_score": 3,
        "evidence_url": "https://api-docs.ecwid.com/reference/overview",
        "confidence": "high",
        "confidence_per_field": {
            "auth_methods": "high",
            "self_serve": "high",
            "api_breadth": "high",
            "mcp_exists": "medium",
            "buildability": "high",
        },
        "source": "manual",
        "tier_used": 0,
        "run_timestamp": TS,
        "research_notes": NOTE,
    },
    {
        "app_name": "Gumroad",
        "category": "Ecommerce",
        "one_liner": "Creator commerce platform for selling digital products, with OAuth2 REST API for products, sales, and subscribers.",
        "auth_methods": ["OAuth2", "API Key"],
        "self_serve": True,
        "trial_available": True,
        "gating_note": "Free to sign up, 10% fee per sale. OAuth2 app registered at app.gumroad.com/oauth/applications.",
        "api_type": "REST",
        "api_breadth": "moderate",
        "mcp_exists": False,
        "mcp_url": None,
        "buildability": "ready",
        "blocker": None,
        "opportunity_score": 3,
        "evidence_url": "https://gumroad.com/api",
        "confidence": "high",
        "confidence_per_field": {
            "auth_methods": "high",
            "self_serve": "high",
            "api_breadth": "high",
            "mcp_exists": "medium",
            "buildability": "high",
        },
        "source": "manual",
        "tier_used": 0,
        "run_timestamp": TS,
        "research_notes": NOTE,
    },
    {
        "app_name": "Amazon Selling Partner",
        "category": "Ecommerce",
        "one_liner": "Amazon's SP-API for sellers — covers listings, orders, inventory, fulfillment, and advertising.",
        "auth_methods": ["OAuth2"],
        "self_serve": True,
        "trial_available": False,
        "gating_note": "Requires active Amazon Seller or Vendor account. LWA (Login with Amazon) OAuth2. App registration via Seller Central.",
        "api_type": "REST",
        "api_breadth": "broad",
        "mcp_exists": False,
        "mcp_url": None,
        "buildability": "ready",
        "blocker": "Requires active Amazon Seller or Vendor account to register an application.",
        "opportunity_score": 4,
        "evidence_url": "https://developer-docs.amazon.com/sp-api/docs/what-is-the-selling-partner-api",
        "confidence": "high",
        "confidence_per_field": {
            "auth_methods": "high",
            "self_serve": "medium",
            "api_breadth": "high",
            "mcp_exists": "high",
            "buildability": "high",
        },
        "source": "manual",
        "tier_used": 0,
        "run_timestamp": TS,
        "research_notes": NOTE,
    },

    # ── Data SEO and Scraping ─────────────────────────────────────────────────
    {
        "app_name": "DataForSEO",
        "category": "Data SEO and Scraping",
        "one_liner": "SEO data API covering SERP, keywords, backlinks, on-page data with pay-per-use pricing.",
        "auth_methods": ["Basic Auth"],
        "self_serve": True,
        "trial_available": True,
        "gating_note": "Free trial with $1 credit on signup. Pay-per-use after that. Credentials generated immediately.",
        "api_type": "REST",
        "api_breadth": "broad",
        "mcp_exists": False,
        "mcp_url": None,
        "buildability": "ready",
        "blocker": None,
        "opportunity_score": 4,
        "evidence_url": "https://docs.dataforseo.com/",
        "confidence": "high",
        "confidence_per_field": {
            "auth_methods": "high",
            "self_serve": "high",
            "api_breadth": "high",
            "mcp_exists": "medium",
            "buildability": "high",
        },
        "source": "manual",
        "tier_used": 0,
        "run_timestamp": TS,
        "research_notes": NOTE,
    },
    {
        "app_name": "SE Ranking",
        "category": "Data SEO and Scraping",
        "one_liner": "SEO platform covering rank tracking, keyword research, backlinks, and site audit — with REST API.",
        "auth_methods": ["API Key"],
        "self_serve": True,
        "trial_available": True,
        "gating_note": "14-day free trial. API key available on paid plans starting at $52/mo.",
        "api_type": "REST",
        "api_breadth": "moderate",
        "mcp_exists": False,
        "mcp_url": None,
        "buildability": "ready",
        "blocker": "API access requires paid plan (not available on free trial).",
        "opportunity_score": 3,
        "evidence_url": "https://seranking.com/api.html",
        "confidence": "high",
        "confidence_per_field": {
            "auth_methods": "high",
            "self_serve": "high",
            "api_breadth": "medium",
            "mcp_exists": "medium",
            "buildability": "high",
        },
        "source": "manual",
        "tier_used": 0,
        "run_timestamp": TS,
        "research_notes": NOTE,
    },
    {
        "app_name": "Ahrefs",
        "category": "Data SEO and Scraping",
        "one_liner": "SEO toolset for backlink analysis, keyword research, and site audits with a REST API on paid plans.",
        "auth_methods": ["API Key"],
        "self_serve": False,
        "trial_available": False,
        "gating_note": "API access requires Advanced or Enterprise plan ($399+/mo). No free tier for API.",
        "api_type": "REST",
        "api_breadth": "moderate",
        "mcp_exists": False,
        "mcp_url": None,
        "buildability": "needs_outreach",
        "blocker": "API only available on Advanced ($399/mo) or Enterprise plans — no trial or self-serve API access.",
        "opportunity_score": 3,
        "evidence_url": "https://ahrefs.com/api",
        "confidence": "high",
        "confidence_per_field": {
            "auth_methods": "high",
            "self_serve": "high",
            "api_breadth": "medium",
            "mcp_exists": "high",
            "buildability": "high",
        },
        "source": "manual",
        "tier_used": 0,
        "run_timestamp": TS,
        "research_notes": NOTE,
    },
    {
        "app_name": "MrScraper",
        "category": "Data SEO and Scraping",
        "one_liner": "AI-powered web scraper with REST API for extracting structured data from any website.",
        "auth_methods": ["API Key"],
        "self_serve": True,
        "trial_available": True,
        "gating_note": "Free plan with 1000 credits/month. API key available immediately after signup.",
        "api_type": "REST",
        "api_breadth": "moderate",
        "mcp_exists": False,
        "mcp_url": None,
        "buildability": "ready",
        "blocker": None,
        "opportunity_score": 3,
        "evidence_url": "https://docs.mrscraper.com/",
        "confidence": "medium",
        "confidence_per_field": {
            "auth_methods": "high",
            "self_serve": "high",
            "api_breadth": "medium",
            "mcp_exists": "medium",
            "buildability": "high",
        },
        "source": "manual",
        "tier_used": 0,
        "run_timestamp": TS,
        "research_notes": NOTE,
    },
    {
        "app_name": "Waterfall.io",
        "category": "Data SEO and Scraping",
        "one_liner": "B2B data enrichment platform using a waterfall approach across multiple data providers via REST API.",
        "auth_methods": ["API Key"],
        "self_serve": True,
        "trial_available": True,
        "gating_note": "Free trial credits on signup. API key generated from dashboard after account creation.",
        "api_type": "REST",
        "api_breadth": "narrow",
        "mcp_exists": False,
        "mcp_url": None,
        "buildability": "ready",
        "blocker": None,
        "opportunity_score": 3,
        "evidence_url": "https://waterfall.io/docs",
        "confidence": "medium",
        "confidence_per_field": {
            "auth_methods": "high",
            "self_serve": "medium",
            "api_breadth": "medium",
            "mcp_exists": "medium",
            "buildability": "medium",
        },
        "source": "manual",
        "tier_used": 0,
        "run_timestamp": TS,
        "research_notes": NOTE,
    },
    {
        "app_name": "Clay",
        "category": "Data SEO and Scraping",
        "one_liner": "Data enrichment and outreach automation platform with REST API for table management and enrichment.",
        "auth_methods": ["API Key"],
        "self_serve": True,
        "trial_available": True,
        "gating_note": "Free plan with 100 credits. API key from account settings. Paid plans from $149/mo.",
        "api_type": "REST",
        "api_breadth": "moderate",
        "mcp_exists": False,
        "mcp_url": None,
        "buildability": "ready",
        "blocker": None,
        "opportunity_score": 4,
        "evidence_url": "https://docs.clay.com/api-reference/introduction",
        "confidence": "high",
        "confidence_per_field": {
            "auth_methods": "high",
            "self_serve": "high",
            "api_breadth": "medium",
            "mcp_exists": "medium",
            "buildability": "high",
        },
        "source": "manual",
        "tier_used": 0,
        "run_timestamp": TS,
        "research_notes": NOTE,
    },

    # ── Developer Infra and Data ──────────────────────────────────────────────
    {
        "app_name": "MongoDB Atlas",
        "category": "Developer Infra and Data",
        "one_liner": "MongoDB's cloud database service with a REST Admin API covering clusters, users, projects, and data.",
        "auth_methods": ["API Key"],
        "self_serve": True,
        "trial_available": True,
        "gating_note": "Free M0 cluster on signup. API keys (public/private pair) generated from Atlas project settings.",
        "api_type": "REST",
        "api_breadth": "broad",
        "mcp_exists": True,
        "mcp_url": "https://github.com/mongodb-labs/mongodb-mcp-server",
        "buildability": "ready",
        "blocker": None,
        "opportunity_score": 5,
        "evidence_url": "https://www.mongodb.com/docs/atlas/api/atlas-admin-api-ref/",
        "confidence": "high",
        "confidence_per_field": {
            "auth_methods": "high",
            "self_serve": "high",
            "api_breadth": "high",
            "mcp_exists": "high",
            "buildability": "high",
        },
        "source": "manual",
        "tier_used": 0,
        "run_timestamp": TS,
        "research_notes": NOTE,
    },
    {
        "app_name": "Neo4j",
        "category": "Developer Infra and Data",
        "one_liner": "Leading graph database with REST API, Bolt protocol, and a published MCP server for AI agent integration.",
        "auth_methods": ["Basic Auth", "Bearer Token"],
        "self_serve": True,
        "trial_available": True,
        "gating_note": "AuraDB free tier available (cloud). Self-hosted community edition is free. API access immediate.",
        "api_type": "REST",
        "api_breadth": "broad",
        "mcp_exists": True,
        "mcp_url": "https://github.com/neo4j-contrib/mcp-neo4j",
        "buildability": "ready",
        "blocker": None,
        "opportunity_score": 4,
        "evidence_url": "https://neo4j.com/docs/http-api/current/",
        "confidence": "high",
        "confidence_per_field": {
            "auth_methods": "high",
            "self_serve": "high",
            "api_breadth": "high",
            "mcp_exists": "high",
            "buildability": "high",
        },
        "source": "manual",
        "tier_used": 0,
        "run_timestamp": TS,
        "research_notes": NOTE,
    },

    # ── Productivity and Project Management ───────────────────────────────────
    {
        "app_name": "Coda",
        "category": "Productivity and Project Management",
        "one_liner": "Collaborative doc and database platform with a REST API for docs, tables, rows, and formulas.",
        "auth_methods": ["API Key"],
        "self_serve": True,
        "trial_available": True,
        "gating_note": "Free plan available. API key generated from account settings at coda.io/account.",
        "api_type": "REST",
        "api_breadth": "moderate",
        "mcp_exists": False,
        "mcp_url": None,
        "buildability": "ready",
        "blocker": None,
        "opportunity_score": 3,
        "evidence_url": "https://coda.io/developers/apis/v1",
        "confidence": "high",
        "confidence_per_field": {
            "auth_methods": "high",
            "self_serve": "high",
            "api_breadth": "high",
            "mcp_exists": "medium",
            "buildability": "high",
        },
        "source": "manual",
        "tier_used": 0,
        "run_timestamp": TS,
        "research_notes": NOTE,
    },
    {
        "app_name": "Smartsheet",
        "category": "Productivity and Project Management",
        "one_liner": "Enterprise project management and work execution platform with a broad REST API.",
        "auth_methods": ["OAuth2", "API Key"],
        "self_serve": True,
        "trial_available": True,
        "gating_note": "30-day free trial. OAuth2 app registration or personal access token from account settings.",
        "api_type": "REST",
        "api_breadth": "broad",
        "mcp_exists": False,
        "mcp_url": None,
        "buildability": "ready",
        "blocker": None,
        "opportunity_score": 3,
        "evidence_url": "https://smartsheet.com/developers/api-documentation",
        "confidence": "high",
        "confidence_per_field": {
            "auth_methods": "high",
            "self_serve": "high",
            "api_breadth": "high",
            "mcp_exists": "medium",
            "buildability": "high",
        },
        "source": "manual",
        "tier_used": 0,
        "run_timestamp": TS,
        "research_notes": NOTE,
    },

    # ── Finance and Fintech ───────────────────────────────────────────────────
    {
        "app_name": "Binance",
        "category": "Finance and Fintech",
        "one_liner": "World's largest crypto exchange with a REST and WebSocket API for trading, market data, and account management.",
        "auth_methods": ["API Key"],
        "self_serve": True,
        "trial_available": True,
        "gating_note": "Free account creation. API key generated from Binance account security settings. Testnet available.",
        "api_type": "REST",
        "api_breadth": "broad",
        "mcp_exists": False,
        "mcp_url": None,
        "buildability": "ready",
        "blocker": None,
        "opportunity_score": 4,
        "evidence_url": "https://binance-docs.github.io/apidocs/spot/en/",
        "confidence": "high",
        "confidence_per_field": {
            "auth_methods": "high",
            "self_serve": "high",
            "api_breadth": "high",
            "mcp_exists": "medium",
            "buildability": "high",
        },
        "source": "manual",
        "tier_used": 0,
        "run_timestamp": TS,
        "research_notes": NOTE,
    },

    # ── AI Research and Media ─────────────────────────────────────────────────
    {
        "app_name": "Otter AI",
        "category": "AI Research and Media",
        "one_liner": "AI meeting transcription and notes tool — no public API; integrations via Zapier/webhooks only.",
        "auth_methods": ["None"],
        "self_serve": False,
        "trial_available": True,
        "gating_note": "No public REST API available. Enterprise plan offers limited webhook access. No self-serve API.",
        "api_type": "None",
        "api_breadth": "none",
        "mcp_exists": False,
        "mcp_url": None,
        "buildability": "not_buildable",
        "blocker": "No public API — integrations only available via Zapier or enterprise webhooks.",
        "opportunity_score": 1,
        "evidence_url": "https://help.otter.ai/hc/en-us/articles/360060426892",
        "confidence": "high",
        "confidence_per_field": {
            "auth_methods": "high",
            "self_serve": "high",
            "api_breadth": "high",
            "mcp_exists": "high",
            "buildability": "high",
        },
        "source": "manual",
        "tier_used": 0,
        "run_timestamp": TS,
        "research_notes": NOTE,
    },
    {
        "app_name": "Fathom",
        "category": "AI Research and Media",
        "one_liner": "AI meeting recorder and highlight tool — no public API; export via integrations only.",
        "auth_methods": ["None"],
        "self_serve": False,
        "trial_available": True,
        "gating_note": "No public API. Data export via CRM integrations (HubSpot, Salesforce). No developer access.",
        "api_type": "None",
        "api_breadth": "none",
        "mcp_exists": False,
        "mcp_url": None,
        "buildability": "not_buildable",
        "blocker": "No public API — no developer portal or API documentation available.",
        "opportunity_score": 1,
        "evidence_url": "https://fathom.video/integrations",
        "confidence": "high",
        "confidence_per_field": {
            "auth_methods": "high",
            "self_serve": "high",
            "api_breadth": "high",
            "mcp_exists": "high",
            "buildability": "high",
        },
        "source": "manual",
        "tier_used": 0,
        "run_timestamp": TS,
        "research_notes": NOTE,
    },
    {
        "app_name": "Consensus",
        "category": "AI Research and Media",
        "one_liner": "AI-powered academic search engine that finds evidence in research papers — offers a REST API.",
        "auth_methods": ["API Key"],
        "self_serve": True,
        "trial_available": True,
        "gating_note": "API available on paid plans. Free tier for web app; API access from $9.99/mo premium.",
        "api_type": "REST",
        "api_breadth": "narrow",
        "mcp_exists": False,
        "mcp_url": None,
        "buildability": "ready",
        "blocker": None,
        "opportunity_score": 3,
        "evidence_url": "https://consensus.app/home/blog/consensus-api/",
        "confidence": "medium",
        "confidence_per_field": {
            "auth_methods": "high",
            "self_serve": "medium",
            "api_breadth": "medium",
            "mcp_exists": "medium",
            "buildability": "medium",
        },
        "source": "manual",
        "tier_used": 0,
        "run_timestamp": TS,
        "research_notes": NOTE,
    },
    {
        "app_name": "Reducto",
        "category": "AI Research and Media",
        "one_liner": "Document parsing API that extracts structured data from PDFs, spreadsheets, and images using AI.",
        "auth_methods": ["API Key"],
        "self_serve": True,
        "trial_available": True,
        "gating_note": "Free tier with 50 pages/day. API key generated immediately after signup at reducto.ai.",
        "api_type": "REST",
        "api_breadth": "moderate",
        "mcp_exists": False,
        "mcp_url": None,
        "buildability": "ready",
        "blocker": None,
        "opportunity_score": 4,
        "evidence_url": "https://docs.reducto.ai/",
        "confidence": "high",
        "confidence_per_field": {
            "auth_methods": "high",
            "self_serve": "high",
            "api_breadth": "medium",
            "mcp_exists": "medium",
            "buildability": "high",
        },
        "source": "manual",
        "tier_used": 0,
        "run_timestamp": TS,
        "research_notes": NOTE,
    },
    {
        "app_name": "YouTube Transcript",
        "category": "AI Research and Media",
        "one_liner": "Third-party API service for fetching YouTube video transcripts and captions programmatically.",
        "auth_methods": ["API Key"],
        "self_serve": True,
        "trial_available": True,
        "gating_note": "Free tier with 100 requests/month. API key generated on signup at transcriptapi.com.",
        "api_type": "REST",
        "api_breadth": "narrow",
        "mcp_exists": False,
        "mcp_url": None,
        "buildability": "ready",
        "blocker": None,
        "opportunity_score": 3,
        "evidence_url": "https://www.transcriptapi.com/docs",
        "confidence": "medium",
        "confidence_per_field": {
            "auth_methods": "high",
            "self_serve": "high",
            "api_breadth": "medium",
            "mcp_exists": "medium",
            "buildability": "high",
        },
        "source": "manual",
        "tier_used": 0,
        "run_timestamp": TS,
        "research_notes": NOTE,
    },
    {
        "app_name": "Grain",
        "category": "AI Research and Media",
        "one_liner": "AI meeting recorder that clips highlights and syncs notes to CRMs — limited API, enterprise only.",
        "auth_methods": ["OAuth2"],
        "self_serve": False,
        "trial_available": True,
        "gating_note": "Free plan for recording. API access is enterprise-only — requires contacting sales for credentials.",
        "api_type": "REST",
        "api_breadth": "narrow",
        "mcp_exists": False,
        "mcp_url": None,
        "buildability": "needs_outreach",
        "blocker": "API access requires enterprise plan — contact sales required, no self-serve API.",
        "opportunity_score": 2,
        "evidence_url": "https://grain.com/developers",
        "confidence": "medium",
        "confidence_per_field": {
            "auth_methods": "medium",
            "self_serve": "high",
            "api_breadth": "medium",
            "mcp_exists": "medium",
            "buildability": "high",
        },
        "source": "manual",
        "tier_used": 0,
        "run_timestamp": TS,
        "research_notes": NOTE,
    },
]


def write_stubs():
    written = 0
    for stub in STUBS:
        app_name = stub["app_name"]
        filename = app_name.lower().replace(" ", "_").replace(".", "_") + ".json"
        path = RAW_DIR / filename
        path.write_text(json.dumps(stub, indent=2))
        print(f"  ✓ {app_name}")
        written += 1
    print(f"\n{written} stubs written to data/raw/")


if __name__ == "__main__":
    write_stubs()
